import type { Organization, SocialMediaTeam,  Task, Template, Plan, TaskActivity, TeamMember } from "./types"

// Mock data for development - replace with real database queries later

export const MOCK_ORGANIZATION = {
    id: "org-1",
    name: "Tech Startup Inc",
    email: "contact@techstartup.com",
    status: "active",
    planId: "plan-1",
    createdAt: new Date("2024-01-15"),
    joinedAt: new Date("2024-01-15"),
    plan: "professional",
    teamId: "team-1",
    memberCount: 25,
    platformName: "Twitter"
  }

export const MOCK_ORGANIZATIONS: Organization[] = [
  {
    id: "org-1",
    name: "Tech Startup Inc",
    email: "contact@techstartup.com",
    status: "active",
    planId: "plan-1",
    createdAt: new Date("2024-01-15"),
    joinedAt: new Date("2024-01-15"),
    plan: "professional",
    teamId: "team-1",
    memberCount: 25,
    platformName: "Twitter"
  },
  {
    id: "org-2",
    name: "Marketing Agency Co",
    email: "hello@marketingagency.com",
    status: "active",
    planId: "plan-2",
    createdAt: new Date("2024-02-20"),
    joinedAt: new Date("2024-02-20"),
    plan: "professional",
    teamId: "team-2",
    memberCount: 50,
    platformName: "Instagram"
  },
  {
    id: "org-3",
    name: "E-commerce Store",
    email: "info@ecommerce.com",
    status: "pending",
    createdAt: new Date("2024-03-10"),
    joinedAt: new Date("2024-03-10"),
    plan: "basic",
    teamId: "team-1",
    planId: "plan-1",
    memberCount: 10,
    platformName: "Facebook"
  },
  {
    id: "org-4",
    name: "Fashion Brand Co",
    email: "contact@fashionbrand.com",
    status: "active",
    planId: "plan-3",
    createdAt: new Date("2024-03-15"),
    joinedAt: new Date("2024-03-15"),
    plan: "enterprise",
    teamId: "team-2",
    memberCount: 100,
    platformName: "Instagram"
  },
  {
    id: "org-5",
    name: "Local Restaurant",
    email: "info@localrestaurant.com",
    status: "inactive",
    planId: "plan-1",
    createdAt: new Date("2024-01-01"),
    joinedAt: new Date("2024-01-01"),
    plan: "basic",
    teamId: "team-1",
    memberCount: 5,
    platformName: "Facebook"
  }
]

export const MOCK_TEAMS: SocialMediaTeam[] = [
  {
    id: "team-1",
    name: "Content Creation Team",
    description: "Responsible for creating and managing social media content",
    status: "active",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    memberCount: 3
  },
  {
    id: "team-2",
    name: "Design Team",
    description: "Handles visual design for social media posts",
    status: "active",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    memberCount: 1
  },
]

export const MOCK_TEAM_MEMBERS: TeamMember[] = [
  {
    id: "2",
    teamId: "team-1",
    name: "Sarah Johnson",
    email: "team@platform.com",
    role: "member",
    status: "active",
    joinedAt: new Date("2024-01-02"),
  },
  {
    id: "4",
    teamId: "team-1",
    name: "John Smith",
    email: "john@platform.com",
    role: "lead",
    status: "active",
    joinedAt: new Date("2024-01-05"),
  },
  {
    id: "5",
    teamId: "team-1",
    name: "Emily Davis",
    email: "emily@platform.com",
    role: "member",
    status: "active",
    joinedAt: new Date("2024-01-10"),
  },
  {
    id: "6",
    teamId: "team-2",
    name: "Mike Wilson",
    email: "mike@platform.com",
    role: "manager",
    status: "active",
    joinedAt: new Date("2024-01-16"),
  },
] as const

export const Mock_Task =  {
    id: "task-1",
    title: "Create Product Launch Post",
    description: "Design a social media post for our upcoming product launch",
    organizationId: "org-1",
    organizationName: "Tech Startup Inc",
    assignedTo: "2",
    assignedToName: "Sarah Johnson",
    status: "in_progress",
    priority: "high",
    dueDate: new Date("2024-04-15"),
    createdAt: new Date("2024-04-01"),
  }

export const MOCK_TASKS: Task[] = [
  {
    id: "task-1",
    title: "Create Product Launch Post",
    description: "Design a social media post for our upcoming product launch",
    organizationId: "org-1",
    organizationName: "Tech Startup Inc",
    assignedTo: "2",
    assignedToName: "Sarah Johnson",
    status: "in_progress",
    priority: "high",
    dueDate: new Date("2024-04-15"),
    createdAt: new Date("2024-04-01"),
  },
  {
    id: "task-2",
    title: "Design Marketing Campaign",
    description: "Create a series of social media posts for the upcoming marketing campaign",
    organizationId: "org-2",
    organizationName: "Marketing Agency Co",
    assignedTo: "2",
    assignedToName: "Sarah Johnson",
    status: "pending",
    priority: "medium",
    dueDate: new Date("2024-04-20"),
    createdAt: new Date("2024-04-05"),
  },
  {
    id: "task-3",
    title: "Summer Collection Announcement",
    description: "Design social media content for the summer collection launch",
    organizationId: "org-1",
    organizationName: "Tech Startup Inc",
    assignedTo: "4",
    assignedToName: "John Smith",
    status: "completed",
    priority: "low",
    dueDate: new Date("2024-04-10"),
    createdAt: new Date("2024-03-28"),
  },
]

export const MOCK_TEMPLATES: Template[] = [
  {
    id: "template-1",
    organizationId: "org-1",
    planId: "plan-1",
    content: "Exciting news! We're launching our new product line next week. Stay tuned for amazing deals!",
    imageUrl: "/product-launch.png",
    status: "submitted",
    createdBy: "2",
    createdAt: new Date("2024-04-01"),
  },
  {
    id: "template-2",
    organizationId: "org-2",
    planId: "plan-2",
    content: "Join us for our exclusive webinar on digital marketing strategies. Limited spots available!",
    status: "approved",
    createdBy: "2",
    createdAt: new Date("2024-03-25"),
    approvedAt: new Date("2024-03-28"),
  },
  {
    id: "template-3",
    organizationId: "org-1",
    planId: "plan-1",
    content: "Thank you for being part of our community! Here's a special discount code just for you: SAVE20",
    status: "published",
    createdBy: "4",
    createdAt: new Date("2024-03-20"),
    approvedAt: new Date("2024-03-22"),
    publishedAt: new Date("2024-03-23"),
  },
  {
    id: "template-4",
    organizationId: "org-1",
    planId: "plan-1",
    content: "Check out our summer collection! Fresh styles for the season ahead.",
    imageUrl: "/summer-collection.png",
    status: "rejected",
    feedback:
      "The design looks good, but we need to match our brand guidelines more closely. Please refer to the attached brand style guide and color palette.",
    feedbackImages: ["/brand-color-palette-reference.jpg", "/social-media-design-example.jpg"],
    createdBy: "2",
    createdAt: new Date("2024-04-08"),
  },
]

export const MOCK_PLANS: Plan[] = [
  {
    id: "plan-1",
    name: "Starter",
    description: "Perfect for small businesses getting started with social media",
    price: 99,
    features: ["5 posts per month", "1 social platform", "Basic analytics", "Email support"],
    postsPerMonth: 5,
  },
  {
    id: "plan-2",
    name: "Professional",
    description: "Ideal for growing businesses with active social presence",
    price: 299,
    features: [
      "15 posts per month",
      "3 social platforms",
      "Advanced analytics",
      "Priority support",
      "Content calendar",
    ],
    postsPerMonth: 15,
  },
  {
    id: "plan-3",
    name: "Enterprise",
    description: "For large organizations with comprehensive social media needs",
    price: 599,
    features: [
      "Unlimited posts",
      "All social platforms",
      "Custom analytics",
      "Dedicated account manager",
      "API access",
      "White-label options",
    ],
    postsPerMonth: 999,
  },
]

export const MOCK_TASK_ACTIVITIES: TaskActivity[] = [
  // Task 1 activities - showing complete cycle
  {
    id: "activity-1",
    taskId: "task-1",
    type: "created",
    performedBy: "1",
    performedByRole: "super_admin",
    timestamp: new Date("2024-04-01T09:00:00"),
    details: "Task created and assigned to Sarah Johnson",
  },
  {
    id: "activity-2",
    taskId: "task-1",
    type: "template_submitted",
    performedBy: "2",
    performedByRole: "social_media_team",
    timestamp: new Date("2024-04-02T14:30:00"),
    details: "Initial template submitted for review",
    templateId: "template-1",
  },
  {
    id: "activity-3",
    taskId: "task-1",
    type: "feedback_provided",
    performedBy: "3",
    performedByRole: "organization",
    timestamp: new Date("2024-04-03T10:15:00"),
    details: "Organization provided feedback on template",
    feedback:
      "The content looks great, but can we change the call-to-action to be more urgent? Also, please use our brand colors in the image.",
    changes: "Requested changes to CTA and brand colors",
  },
  {
    id: "activity-3b",
    taskId: "task-1",
    type: "comment",
    performedBy: "3",
    performedByRole: "organization",
    timestamp: new Date("2024-04-03T11:00:00"),
    details: "Organization shared reference images",
    comment: "Here are some examples of the brand colors and style we'd like to see",
    images: ["/brand-color-palette-reference.jpg", "/social-media-design-example.jpg"],
  },
  {
    id: "activity-4",
    taskId: "task-1",
    type: "template_revised",
    performedBy: "2",
    performedByRole: "social_media_team",
    timestamp: new Date("2024-04-04T11:00:00"),
    details: "Template revised based on feedback",
    templateId: "template-1",
    changes: "Updated CTA to 'Don't miss out!' and applied brand colors to image",
  },
  {
    id: "activity-4b",
    taskId: "task-1",
    type: "comment",
    performedBy: "2",
    performedByRole: "social_media_team",
    timestamp: new Date("2024-04-04T14:30:00"),
    details: "Team member shared updated design mockups",
    comment: "I've created a few variations with your brand colors. Let me know which one works best!",
    images: [
      "/social-media-post-design-variation-1.jpg",
      "/social-media-post-design-variation-2.jpg",
      "/social-media-post-design-variation-3.jpg",
    ],
  },
  {
    id: "activity-5",
    taskId: "task-1",
    type: "feedback_provided",
    performedBy: "3",
    performedByRole: "organization",
    timestamp: new Date("2024-04-05T09:30:00"),
    details: "Organization requested minor adjustments",
    feedback: "Much better! Can we adjust the timing mention from 'next week' to 'this Friday'?",
    changes: "Requested timing adjustment",
  },
  {
    id: "activity-6",
    taskId: "task-1",
    type: "template_revised",
    performedBy: "2",
    performedByRole: "social_media_team",
    timestamp: new Date("2024-04-05T15:45:00"),
    details: "Final revision completed",
    templateId: "template-1",
    changes: "Updated timing to 'this Friday'",
  },
  // Task 2 activities
  {
    id: "activity-7",
    taskId: "task-2",
    type: "created",
    performedBy: "1",
    performedByRole: "super_admin",
    timestamp: new Date("2024-04-05T10:00:00"),
    details: "Task created and assigned to Sarah Johnson",
  },
  // Task 3 activities - completed cycle
  {
    id: "activity-8",
    taskId: "task-3",
    type: "created",
    performedBy: "1",
    performedByRole: "super_admin",
    timestamp: new Date("2024-03-28T09:00:00"),
    details: "Task created and assigned to John Smith",
  },
  {
    id: "activity-9",
    taskId: "task-3",
    type: "template_submitted",
    performedBy: "4",
    performedByRole: "social_media_team",
    timestamp: new Date("2024-03-29T11:00:00"),
    details: "Template submitted for review",
    templateId: "template-3",
  },
  {
    id: "activity-10",
    taskId: "task-3",
    type: "approved",
    performedBy: "3",
    performedByRole: "organization",
    timestamp: new Date("2024-03-30T14:00:00"),
    details: "Template approved by organization",
    feedback: "Perfect! This looks exactly what we need. Please proceed with publishing.",
  },
  {
    id: "activity-11",
    taskId: "task-3",
    type: "published",
    performedBy: "4",
    performedByRole: "social_media_team",
    timestamp: new Date("2024-03-31T10:00:00"),
    details: "Template published to social media platforms",
  },
]
